apiVersion: v1
kind: ReplicationController
metadata:
  name: test1
  labels:
    name: test1
spec:
  replicas: 3
  selector:
    name: test1
  template:
    metadata:
      labels:
        name: test1
    spec:
      containers:
      - name: test1
        image: test1
